name: tuoc
description: TU Orthopedic Calendar Application
version: 2.0.1+1

environment:
  #  sdk: ">=2.1.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  table_calendar: ^2.1.0
  intl: ^0.16.1
  flutter_screenutil: ^1.0.2
  #  http: ^0.13.1
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^0.5.6+3
  objectdb: ^1.0.10+1
  path_provider: ^1.6.5
  flutter_device_type: ^0.2.0
  image_picker: ^0.6.7+22
  image_cropper: ^1.2.1
  flutter_image_compress: ^0.7.0
  cached_network_image: ^2.0.5
#  firebase_crashlytics: ^0.4.0+1
#  get_version: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf